import { Color, Vector3 } from 'three';
import { ThreeSunOptions } from './three-sun.service';

/**
 * Global configuration class for the Three.js Sun system.
 * Provides default parameters for the sun's shader, rotation, and lens flares.
 */
export class ThreeSunConfig {
  baseColor = new Color('#fdf2aa');
  emissiveColor = new Color('#ffb59f');
  hotColor = new Color('#efba03');
  deepColor = new Color('#4f0223');

  geometry = {
    radius: 2,
    segments: 64,
  };

  options: ThreeSunOptions = {
    rotation: {
      direction: new Vector3(0, 1, 0),
      speed: 0,
    },
    shader: {
      baseColor: this.baseColor,
      hotColor: this.hotColor,
      deepColor: this.deepColor,
      distortionStrength: 0.2,
      emissiveStrength: 0.75,
      fbmFrequency: 16,
      brightness: 1.2,
      contrastPower: 2.5,
      fbmScale: 1.8,
      fbmOffset: 0.33,
      emissiveThresholdMin: 0.2,
      emissiveThresholdMax: 0.8,
      emissiveColor: this.emissiveColor,
    },
    solarEruptions: {
      active: true,
      min: {
        count: 4,
        interval: 500,
      },
      max: {
        count: 10,
        interval: 2500,
      },
      flareOptions: {
        min: {
          size: 2,
          lifetime: 2,
          plasmaTrails: 2,
          flareCount: 3,
          turbulance: 0.01,
        },
        max: {
          size: 6,
          lifetime: 8,
          plasmaTrails: 5,
          flareCount: 6,
          turbulance: 1,
        },
        shader: {
          emissiveStrength: 1.2,
          opacity: 1.0,
          distortionScale: 1.0,
          fadeStart: 0.45,
          fadeEnd: 0.49,
          noiseScaleX: 4.0,
          noiseScaleY: 1.5,
          speed: 1.0,
        },
      },
    },
    coronas: [
      {
        active: true,
        depthTest: true,
        zIndex: 1,
        glowColor: this.emissiveColor,
        flareStrength: 1.5,
        baseGlowStrength: 1.45,
        radialFalloff: 2.0,
        flareFalloff: 1.5,
        edgeFadeStart: 0.33,
        edgeFadeEnd: 0.75,
        baseGlowThreshold: 0.2,
        animationSpeed: 1.0,
        size: 6,
        scale: 1,
        speed: 0.1,
        syncWithSun: true,
        wrapRotation: true,
        enablePulsing: false,
        pulseFrequency: 0.234,
        pulseAmplitude: 1,
        enableMultiAxisReaction: true,
        rotationReactivity: 0.3,
        rotationDecay: 0.98,
        reactiveScaling: 0.05,
      },
      {
        active: true,
        depthTest: true,
        zIndex: 2,
        glowColor: this.baseColor,
        flareStrength: 1.5,
        baseGlowStrength: 1.45,
        radialFalloff: 2.0,
        flareFalloff: 1.5,
        edgeFadeStart: 0.2,
        edgeFadeEnd: 0.5,
        baseGlowThreshold: 0.4,
        animationSpeed: .5,
        size: 7,
        scale: 1.5,
        speed: 0.1,
        syncWithSun: true,
        wrapRotation: true,
        enablePulsing: false,
        pulseFrequency: 0.234,
        pulseAmplitude: 1,
        enableMultiAxisReaction: true,
        rotationReactivity: 0.3,
        rotationDecay: 0.98,
        reactiveScaling: 0.05,
      },
      {
        active: true,
        depthTest: true,
        zIndex: 3,
        glowColor: this.hotColor,
        flareStrength: 3,
        baseGlowStrength: 3,
        radialFalloff: 2.0,
        flareFalloff: 1.5,
        edgeFadeStart: 0.2,
        edgeFadeEnd: 0.5,
        baseGlowThreshold: 0.35,
        animationSpeed: -.75,
        size: 8,
        scale: 1.3,
        speed: 0.1,
        syncWithSun: true,
        wrapRotation: true,
        enablePulsing: false,
        pulseFrequency: 0.234,
        pulseAmplitude: 1,
        enableMultiAxisReaction: true,
        rotationReactivity: 0.3,
        rotationDecay: 0.98,
        reactiveScaling: 0.05,
      },
      {
        active: true,
        depthTest: true,
        zIndex: 4,
        glowColor: this.deepColor,
        flareStrength: 1.5,
        baseGlowStrength: 10,
        radialFalloff: -8,
        flareFalloff: 3,
        edgeFadeStart: 0.175,
        edgeFadeEnd: 0.28,
        baseGlowThreshold: .27,
        animationSpeed: 1.0,
        size: 6,
        scale: 2.5,
        speed: 1,
        syncWithSun: true,
        wrapRotation: true,
        enablePulsing: false,
        pulseFrequency: 0.234,
        pulseAmplitude: 1,
        enableMultiAxisReaction: true,
        rotationReactivity: 0.3,
        rotationDecay: 0.98,
        reactiveScaling: 0.05,
      },
    ],
  };
}
